### ISSUE TITLE
help want

### ISSUE THREAD

**Issue by lichunqiang** [angular-class/NG6-starter#17]
Hi, i had download the repo to local, and followed the guide.

but when i ran `gulp`, an error throwed:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\project\ng-starter\node_modules\browser-sync\lib\h
ooks.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

My computer  environment is : 

```
win7
node -v 
v0.12.0
npm -v 
2.11.2

```

**Comment by mrblueblue** [comment]
Looks like gulp wants the npm package immutable.js. Try running `npm install immutable`.

**Comment by lichunqiang** [comment]
yes, your are right.

__but why not run `npm install` everything will be ok - -!__

after npm init, and run gulp, the result is there, but not try to solve the problem..

**Comment by mrblueblue** [comment]
The problem is with the `browser-sync` package. Looks related to this [issue] (https://github.com/BrowserSync/browser-sync/issues/502)

**Comment by danthareja** [comment]
nice find @mrblueblue.

@lichunqiang can you try `npm rm browser-sync && npm install browser-sync`?

**Comment by lichunqiang** [comment]
@mrblueblue @danthareja 

Thanks ~ it's work now
