### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by Cabarfeidh** [angular-class/NG6-starter#46]
Hi, getting the following error trying to run Gulp for the NG6-starter-jspm version. Have I missed the install of a transpiler? From what I can see all the Node modules seem to be in place. Still a novice with this technology, any help would be much appreciated.
Cheers, Colin

E:\AngularJS\ES2015\NG6-starter-jspm>gulp
[20:32:56] Using gulpfile E:\AngularJS\ES2015\NG6-starter-jspm\Gulpfile.js
[20:32:56] Starting 'serve'...
[20:32:56] 'serve' errored after 2.4 ms
[20:32:56] E:\AngularJS\ES2015\NG6-starter-jspm\node_modules\chokidar-socket-emi
tter\server.js:2
const chokidar = require('chokidar')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Gulp.<anonymous> (E:\AngularJS\ES2015\NG6-starter-jspm\Gulpfile.js:38:2)
    at module.exports (E:\AngularJS\ES2015\NG6-starter-jspm\node_modules\gulp\no
de_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (E:\AngularJS\ES2015\NG6-starter-jspm\node_mod
ules\gulp\node_modules\orchestrator\index.js:273:3)

**Comment by fesor** [comment]
check node version: `node --version`. Upgrade to Node4

**Comment by Cabarfeidh** [comment]
Many thanks, I'll give it a go.

**Comment by kmturley** [comment]
If you are running another build of Node, you can get compatibility using the --harmony flag:

    gulp --harmony

As referenced in this answer:
http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode
