### ISSUE TITLE
[JSPM] Unable to calculate canonical name with gulp build

### ISSUE THREAD

**Issue by stephanbureau** [angular-class/NG6-starter#57]
Hi,

Not sure if this topic has been already raised, i got trouble with a fresh clone of the repo (jspm branch) when I tried to  build the app with "gulp build":
```
Error: Unable to calculate canonical name to bundle file:///f:/ng6/NG6-starter/../app.js
    at getCanonicalNamePlain (f:\webapp\ng6\NG6-starter\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:177:13)
    at getCanonicalName (f:\webapp\ng6\NG6-starter\node_modules\jspm\node_modules\systemjs-builder\lib\utils.js:88:19)
    at f:\webapp\ng6\NG6-starter\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:84:38
    at process._tickCallback (node.js:366:9)
```

My relative path problem has been 'solved' when i replaced l.19 in Gulpfile.js by:
```
return path.relative(path.resolve(root), path.resolve(path.join(root, resolvePath, glob)));
```

Does anyone already encounter this issue on windows and solved it in a cleaner way?
Thanks

**Comment by rdehuyss** [comment]
Thx! @stephanbureau Saved me some time!
